
# app.yaml file for GoSkrafl on Google App Engine

runtime: go121

service: moves

instance_class: F1

inbound_services:
- warmup

includes:
- env.yaml

handlers:
- url: /moves
  script: auto
  secure: always
- url: /wordcheck
  script: auto
  secure: always
- url: /_ah/warmup
  script: auto
  secure: always
