
# app.yaml file for GoSkrafl on Google App Engine

runtime: go121

service: moves

instance_class: F1

inbound_services:
- warmup

env_variables:
  PROJECT_ID: explo-dev

handlers:
- url: /moves
  script: auto
  # secure: always
